name: placement_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - imbalanced-learn==0.12.0
      - matplotlib==3.8.0
      - mlflow==2.10.0
      - numpy==1.26.4
      - pandas==2.1.4
      - scikit-learn==1.3.2
      - seaborn==0.13.0