name: placement_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - imbalanced_learn==0.14.0
      - matplotlib==3.10.7
      - mlflow==3.6.0
      - numpy==2.3.5
      - pandas==2.3.3
      - scikit_learn==1.7.2
      - seaborn==0.13.2
